### ISSUE TITLE
Add TSLint instead of JSHint

### ISSUE THREAD

**Issue by jj09** [mrkev/generator-typescript#2]
Hi Kevin ,

What do you think about replacing JSHint with TSLint?
Or just adding TSLint? 
As this is TypeScript app, developer should be more concerned about TypeScript code quality, and treat JavaScript as 'assembly code'.

**Comment by mrkev** [comment]
Certainly will give it a look.
I'm busy rn with the final weeks of the semester but once things clear up a bit I'll look into it 👍

**Comment by mrkev** [comment]
Added TSLint support! Didn't remove the `.jshintrc` just yet because even if it doesn't benefit everyone I don't see it hurting anyone. I've personally once worked on a project that used both JS and TS (probably not ideal, but it happened because frontend / backend). Might delete it sometime in the future. We'll see.
